name: GitHub CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: TestHello
      id: testHello
      uses: ./
      with:
        repoName: meghnasavit/hello-world-javascript-action
        branchName: master
        templateConfigName: TransformerConfig
        templateType: HandleBars
        sourceType: CodePushed
        ClientType: Teams
    - name: PrintOutput
      run: echo steps.testHello.outputs.renderedTemplate
